insert into EDU_GROUP (number, faculty) values ('P1', 'Physics')
insert into EDU_GROUP (number, faculty) values ('M2', 'Math')
insert into EDU_GROUP (number, faculty) values ('S3', 'Science')
insert into EDU_GROUP (number, faculty) values ('G4', 'Genetic')
insert into EDU_GROUP (number, faculty) values ('C5', 'Chemical')

insert into STUDENT (firstName, lastName, middleName, dob, group_fk) values ('A', 'B', 'C', null, 1)
insert into STUDENT (firstName, lastName, middleName, dob, group_fk) values ('D', 'E', 'F', null, 1)
insert into STUDENT (firstName, lastName, middleName, dob, group_fk) values ('J', 'H', 'I', null, 3)
insert into STUDENT (firstName, lastName, middleName, dob, group_fk) values ('G', 'K', 'L', null, 2)